2016/07/21 01:38:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:38:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:38:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:39:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:39:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:39:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:39:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:40:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 01:43:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:11:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:11:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:11:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:11:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:12:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:12:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:12:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:27:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:37:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:37:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:37:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:37:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:37:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:37:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:41:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:42:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:42:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:42:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:42:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:42:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:42:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 11:42:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 14:57:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 14:57:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/index.php?r=gii
---
2016/07/21 16:10:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/?r=gii
---
2016/07/21 16:27:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/?r=gii
---
2016/07/21 16:33:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/default/login".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/?r=gii/default/login
---
2016/07/21 16:34:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/?r=gii
---
2016/07/21 16:34:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/?r=gii
---
2016/07/21 16:34:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/?r=gii
---
2016/07/21 16:34:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/?r=gii
---
2016/07/21 16:34:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/?r=gii
---
2016/07/21 16:35:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/?r=gii
---
2016/07/21 16:35:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /usr/share/nginx/html/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yii/blog/?r=gii
---
2016/07/21 16:57:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: could not find driver' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:25 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:26 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:26 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:26 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:26 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
2016/07/21 16:59:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /usr/share/nginx/html/yii/framework/db/CDbConnection.php:399
Stack trace:
#0 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /usr/share/nginx/html/yii/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /usr/share/nginx/html/yii/framework/base/CModule.php(394): CDbConnection->init()
#3 /usr/share/nginx/html/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /usr/share/nginx/html/yii/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /usr/share/nginx/html/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /usr/share/nginx/html/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /usr/share/nginx/html/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /usr/share/nginx/html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /usr/share/nginx/html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /usr/share/nginx/html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(282): CController->run('index')
#13 /usr/share/nginx/html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /usr/share/nginx/html/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /usr/share/nginx/html/yii/blog/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/blog/index.php?r=gii/model/index
HTTP_REFERER=http://127.0.0.1/yii/blog/index.php?r=gii/controller/index
---
